---

# - include: debug.yml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks.
  include_tasks: "setup-{{ ansible_os_family }}.yml"
