---

- name: Ensure virtualization software (KVM) is installed.
  yum:
    name: "{{ minikube_virt_packages }}"
    state: present

- name: Ensure libvirtd is enabled and started.
  service:
    name: libvirtd
    enabled: true
    state: started

- name: Unsure user ak is appended to the libvirt group.
  user:
    name: "{{ minikube_user_name }}"
    append: true
    groups: libvirt

- name: Ensure containers' management packages are installed.
  yum:
    name: "{{ minikube_containers_packages }}"
    state: present

- name: Ensure VMs' management packages are installed.
  yum:
    name: "{{ minikube_vm_packages }}"
    state: present

- name: Ensure minikube is installed.
  yum:
    name: "{{ minikube_rpm_url }}"
    state: present

- name: Ensure k8s' repo is present.
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Ensure kubectl is installed.
  yum:
    name: kubectl
    state: present

